import Navbar from "@/components/layout/Navbar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import BrowseCategories from "@/components/BrowseCategories/BrowseCategories";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col gap-4"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex flex-col items-center p-2">
            <Navbar />
            <BrowseCategories />
          </header>
          {children}
          <footer className="p-2">Created By patryk</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
